model_params:
  model: PCTCFS
  pretrain_dir: bert-large-uncased
  num_categories: 6
  num_hosts: 65
  stats_dim: 83
  num_classes: 30
  pad_token: 0

# distributed_params:
#   opt_level: O1
#   syncbn: True

stages:
  state_params:
    main_metric: spearman
    minimize_metric: False

  data_params:
    num_workers: &nw 2
    batch_size: *nw
    tokenizer: bert-large-uncased

  criterion_params:
    criterion: BCEWithLogitsLoss

  callbacks_params:
    loss:
      callback: CriterionCallback
      input_key: targets

    optim:
      callback: OptimizerCallback
      accumulation_steps: 16

    spearman:
      callback: SpearmanScoreCallback
      classes: 30

    saver:
      callback: CheckpointCallback
    
    early_stopping:
      callback: EarlyStoppingCallback
      patience: 3
      metric: spearman
      minimize: False

  stage1:
    state_params:
      num_epochs: 10
    
    optimizer_params:
      optimizer: Adam
      lr: 0.00003
      betas: &betas [0.9, 0.98]
      eps: &eps 0.000000001