model_params:
  model: patch_model_with_embedding
  embedding_file: data/embeddings/glove_crawl_wikinews_emb.pkl
  params:
    model: MultiInputLstmGruAttention
    embedding_size: 60668
    embedding_dim: 900
    category_embedding_size: 6
    category_embedding_dim: 16
    host_embedding_size: 65
    host_embedding_dim: 32
    hidden_size: 128
    out_rnn_size: 128
    dropout_rate: 0.3
    num_classes: 30

stages:
  state_params:
    main_metric: spearman
    minimize_metric: False

  data_params:
    num_workers: 16
    batch_size: 34
    tokenizer_dir: data/vocab.json
    seq_percentile: 90
    train_pickle: data/train.pkl
    valid_pickle: data/valid.pkl

  criterion_params:
    criterion: BCEWithLogitsLoss

  callbacks_params:
    loss:
      callback: CriterionCallback

    optim:
      callback: OptimizerCallback
      grad_clip_params:
        func: clip_grad_norm
        max_norm: 1

    spearman:
      callback: SpearmanScoreCallback

    saver:
      callback: CheckpointCallback

  stage1:
    state_params:
      num_epochs: 30

    optimizer_params:
      optimizer: RAdam
      lr: 0.01

  stage2:
    state_params:
      num_epochs: 20

    optimizer_params:
      optimizer: RAdam
      lr: 0.001

  finetune:
    state_params:
      num_epochs: 5

    optimizer_params:
      optimizer: RAdam
      lr: 0.0001
