model_params:
  model: TransfModel
  pretrain_dir: bert-base-uncased
  num_classes: 30

stages:
  state_params:
    main_metric: spearman
    minimize_metric: False

  data_params:
    num_workers: 6
    batch_size: 6
    train_pickle: data/folds/transf_train_0.pkl
    valid_pickle: data/folds/transf_valid_0.pkl
    transformer_dir: data/uncased_L-12_H-768_A-12

  criterion_params:
    criterion: BCEWithLogitsLoss

  callbacks_params:
    loss:
      callback: CriterionCallback
      input_key: targets

    optim:
      callback: OptimizerCallback

    spearman:
      callback: SpearmanScoreCallback
      classes: 30

    saver:
      callback: CheckpointCallback

  stage1:
    state_params:
      num_epochs: 10
    
    optimizer_params:
      optimizer: RAdam
      lr: 0.00002

  stage2:
    state_params:
      num_epochs: 5
    
    optimizer_params:
      optimizer: RAdam
      lr: 0.00001

  stage3:
    state_params:
      num_epochs: 5
    
    optimizer_params:
      optimizer: RAdam
      lr: 0.00001

  stage4:
    state_params:
      num_epochs: 5
    
    optimizer_params:
      optimizer: RAdam
      lr: 0.00001

  stage5:
    state_params:
      num_epochs: 5
    
    optimizer_params:
      optimizer: RAdam
      lr: 0.00001