model_params:
  model: model_from_checkpoint
  checkpoint: logs/folds/tlgkf_2/checkpoints/best.pth
  params:
    model: PooledTransfModel
    pretrain_dir: bert-large-uncased
    num_classes: 30

stages:
  state_params:
    main_metric: spearman
    minimize_metric: False

  data_params:
    num_workers: &nw 2
    batch_size: *nw
    transformer_dir: data/uncased_L-12_H-768_A-12

  criterion_params:
    criterion: BCEWithLogitsLoss

  callbacks_params:
    loss:
      callback: CriterionCallback
      input_key: targets

    optim:
      callback: OptimizerCallback
      accumulation_steps: 16

    spearman:
      callback: SpearmanScoreCallback
      classes: 30

    saver:
      callback: CheckpointCallback

  stage2:
    state_params:
      num_epochs: 10
    
    optimizer_params:
      optimizer: Adam
      lr: 0.00001
