model_params:
  model: PooledLstmTransfModel
  pretrain_dir: bert-base-uncased
  num_classes: 30

stages:
  state_params:
    main_metric: spearman
    minimize_metric: False

  data_params:
    batch_size: &bs 6
    num_workers: *bs
    transformer_dir: data/uncased_L-12_H-768_A-12

  criterion_params:
    criterion: BCEWithLogitsLoss

  callbacks_params:
    loss:
      callback: CriterionCallback
      input_key: targets

    optim:
      callback: OptimizerCallback
      accumulation_steps: 4

    spearman:
      callback: SpearmanScoreCallback
      classes: 30

    saver:
      callback: CheckpointCallback

  stage_freezed_0:
    state_params:
      num_epochs: 2
    
    optimizer_params:
      optimizer: Adam
      lr: 0.0001

  stage1:
    state_params:
      num_epochs: 10
    
    optimizer_params:
      optimizer: Adam
      lr: 0.00003

  stage2:
    state_params:
      num_epochs: 10
    
    optimizer_params:
      optimizer: Adam
      lr: 0.00001

  stage3:
    state_params:
      num_epochs: 10
    
    optimizer_params:
      optimizer: Adam
      lr: 0.000005
